return {
    schema_version = 1,
    required_fields = {
        "schema_version",
        "seq",
        "timestamp",
        "session_id",
        "level",
        "event_id",
        "component",
        "action",
        "outcome",
        "message_key",
        "context",
    },
    context_fields = {
        buffer_type = true,
        check_id = true,
        filetype = true,
        foldlevel = true,
        foldmethod = true,
        line = true,
        path = true,
        reason = true,
        scenario = true,
    },
    fold_outcomes = {
        toggled = true,
        no_fold = true,
        unsupported_buffer = true,
        degraded = true,
        failed = true,
    },
}
