return {
    schema_version = 1,
    scenarios = {
        empty_headless = {
            kind = "headless",
            description = "Empty startup without an attached UI",
        },
        file_headless = {
            kind = "headless",
            description = "Tracked file startup without an attached UI",
        },
        file_ui = {
            kind = "attached_ui",
            description = "Tracked file startup with a real embedded UI",
        },
    },
    modules = {
        ["config.lazy"] = { class = "pre_plugin", owner = "bootstrap" },
        ["config.options"] = { class = "pre_plugin", owner = "LazyVimOptions" },
        ["config.autocmds"] = { class = "lifecycle", owner = "LazyVimAutocmds" },
        ["config.keymaps"] = { class = "lifecycle", owner = "LazyVimKeymaps" },
        ["config.capabilities"] = { class = "eager_service", owner = "config.audit" },
        ["config.i18n"] = { class = "eager_service", owner = "config.lazy" },
        ["config.menu_i18n"] = { class = "eager_service", owner = "config.lazy" },
        ["config.audit"] = { class = "eager_service", owner = "config.lazy" },
        ["config.help"] = { class = "eager_service", owner = "config.lazy" },
        ["config.health"] = { class = "eager_service", owner = "config.lazy" },
        ["config.validation"] = { class = "eager_service", owner = "config.lazy" },
        ["config.commands"] = { class = "eager_service", owner = "config.lazy" },
        ["config.diagnostics"] = { class = "on_demand", owner = "Clarity actions" },
        ["config.actions.catalog"] = { class = "eager_service", owner = "config.menu_i18n" },
        ["config.actions.fold"] = { class = "on_demand", owner = "config.keymaps" },
        ["config.actions.git"] = { class = "on_demand", owner = "config.keymaps" },
        ["config.product_policy"] = { class = "pre_plugin", owner = "plugins.action_surface" },
    },
    capabilities = {
        file_search = {
            surface = "<leader>ff",
            owner = "LazyVim picker",
            profile = "core",
            coverage = "covered",
        },
        text_search = {
            surface = "<leader>fw",
            owner = "config.keymaps",
            profile = "core",
            coverage = "covered",
        },
        explorer = {
            surface = "<leader>e",
            owner = "plugins.neo-tree",
            profile = "core",
            coverage = "covered",
        },
        code_fold = {
            surface = "<leader>cz",
            owner = "config.actions.fold",
            profile = "core",
            coverage = "covered",
        },
        line_wrap = {
            surface = "<leader>uw",
            owner = "config.keymaps",
            profile = "core",
            coverage = "covered",
        },
        terminal = {
            surface = "<leader>tf",
            owner = "plugins.terminal",
            profile = "core",
            coverage = "covered",
        },
        git_hunks = {
            surface = "]h|[h|<leader>ghp",
            owner = "plugins.git",
            profile = "development",
            coverage = "covered",
        },
        lsp_navigation = {
            surface = "gd|gr|gl",
            owner = "LazyVim LSP keymaps",
            profile = "development",
            coverage = "covered",
        },
        formatting = {
            surface = "LazyVim format",
            owner = "plugins.formatting",
            profile = "development",
            coverage = "covered",
        },
        parser = {
            surface = "Tree-sitter highlight/fold",
            owner = "plugins.treesitter",
            profile = "development",
            coverage = "covered",
        },
        recovery = {
            surface = ":ClarityStart|<leader>hh",
            owner = "config.help",
            profile = "core",
            coverage = "covered",
        },
        language = {
            surface = ":ClarityLanguage",
            owner = "config.i18n",
            profile = "core",
            coverage = "covered",
        },
        audit = {
            surface = ":ClarityAudit",
            owner = "config.audit",
            profile = "core",
            coverage = "covered",
        },
        validation = {
            surface = ":ClarityValidate",
            owner = "config.validation",
            profile = "core",
            coverage = "covered",
        },
    },
    checks = {
        {
            id = "CLARITY_RUNTIME_OPTIONS_CONTRACT",
            kind = "module_phase",
            module = "config.options",
            owner = "LazyVimOptions",
            scenarios = { "empty_headless", "file_headless", "file_ui" },
            expected = "User:LazyVimOptions",
            repair = "Keep the nested Clarity runtime visible while LazyVim loads options.",
        },
        {
            id = "CLARITY_RUNTIME_AUTOCMDS_CONTRACT",
            kind = "autocmds_contract",
            module = "config.autocmds",
            owner = "LazyVimAutocmds",
            scenarios = { "file_headless", "file_ui" },
            expected = "loaded at User:LazyVimAutocmds with owned line-number autocmds",
            repair = "Restore natural config.autocmds discovery before file startup completes.",
        },
        {
            id = "CLARITY_RUNTIME_EDITING_DEFAULTS",
            kind = "editing_defaults",
            owner = "config.options",
            scenarios = { "empty_headless", "file_headless", "file_ui" },
            expected = "number=true relativenumber=false wrap=true linebreak=true breakindent=true conceallevel=0",
            repair = "Apply Clarity editing defaults after LazyVim defaults through config.options.",
        },
        {
            id = "CLARITY_RUNTIME_KEYMAP_CONTRACT",
            kind = "keymap_contract",
            module = "config.keymaps",
            owner = "LazyVimKeymaps",
            scenarios = { "file_ui" },
            expected = "loaded at User:LazyVimKeymaps with exact 28 global and seven contextual normal leader actions",
            repair = "Keep the nested runtime visible through UIEnter/VeryLazy and restore Clarity keymaps.",
        },
        {
            id = "CLARITY_RUNTIME_WRAP_CONTRACT",
            kind = "behavior_contract",
            owner = "config.keymaps",
            scenarios = { "file_ui" },
            flags = { "wrap_callback", "wrap_changed", "wrap_restored" },
            expected = "the promoted wrap action changes and restores the real window option",
            repair = "Restore the typed wrap callback and its window-local behavior.",
        },
        {
            id = "CLARITY_RUNTIME_FOLD_CONTRACT",
            kind = "behavior_contract",
            owner = "config.actions.fold",
            scenarios = { "file_ui" },
            flags = {
                "fold_callback",
                "fold_input",
                "fold_initially_closed",
                "fold_open_input_ok",
                "fold_opened",
                "fold_close_input_ok",
                "fold_reclosed",
                "fold_no_fold_ok",
                "fold_cleanup",
            },
            equals = {
                fold_open_outcome = "toggled",
                fold_close_outcome = "toggled",
                fold_no_fold_outcome = "no_fold",
                fold_no_fold_event_id = "CLARITY_FOLD_NO_FOLD",
                fold_no_fold_error = "",
            },
            expected = "real fold input toggles twice and reports a typed no-fold outcome without E5108",
            repair = "Route <leader>cz through config.actions.fold and preserve typed recovery.",
        },
        {
            id = "CLARITY_RUNTIME_LSP_CONTRACT",
            kind = "behavior_contract",
            owner = "nvim-lspconfig + host PATH",
            scenarios = { "file_ui" },
            flags = {
                "context_lsp_started",
                "context_lsp_attached",
                "context_lsp_system_command",
                "context_lsp_keys_ready",
            },
            expected = "a host PATH lua-language-server attaches naturally and owns the curated contextual keys",
            repair = "Install lua-language-server on PATH or repair the nvim-lspconfig system-toolchain route.",
        },
        {
            id = "CLARITY_RUNTIME_GITSIGNS_CONTRACT",
            kind = "behavior_contract",
            owner = "gitsigns.nvim",
            scenarios = { "file_ui" },
            flags = { "context_git_attached", "gitsigns_observation_input" },
            expected = "Gitsigns attaches naturally with navigation and preview only",
            repair = "Restore the curated read-only Gitsigns on_attach delta.",
        },
        {
            id = "CLARITY_RUNTIME_I18N_CONTRACT",
            kind = "behavior_contract",
            owner = "config.i18n",
            scenarios = { "file_ui" },
            flags = { "which_key_loaded", "locale_roundtrip", "locale_behavior_identity" },
            expected = "English to Chinese to English refreshes live labels without changing behavior identity",
            repair = "Refresh localized metadata from ClarityLocaleChanged without replacing callbacks.",
        },
        {
            id = "CLARITY_RUNTIME_EXPLORER_CONTRACT",
            kind = "behavior_contract",
            owner = "plugins.neo-tree",
            scenarios = { "file_ui" },
            flags = {
                "explorer_opened",
                "explorer_exact_count",
                "explorer_within_budget",
                "explorer_mutation_absent",
                "explorer_numbers_hidden",
                "explorer_locale_roundtrip",
                "explorer_keyboard_close",
            },
            expected = "Neo-tree exposes exactly 20 localized observation mappings with no mutation path",
            repair = "Restore the complete curated Neo-tree mapping profile and live locale refresh.",
        },
        {
            id = "CLARITY_RUNTIME_PICKER_CONTRACT",
            kind = "behavior_contract",
            owner = "plugins.ui",
            scenarios = { "file_ui" },
            flags = {
                "picker_opened",
                "picker_within_budget",
                "picker_mutation_absent",
                "picker_locale_roundtrip",
                "picker_keyboard_close",
            },
            expected = "the real files picker stays within 20 mappings per mode and refreshes labels live",
            repair = "Restore the curated Snacks picker profile and remove mutation/export aliases.",
        },
        {
            id = "CLARITY_RUNTIME_UI_CONTRACT",
            kind = "behavior_contract",
            owner = "plugins.ui",
            scenarios = { "file_ui" },
            flags = { "dashboard_exact", "dashboard_locale_roundtrip", "dashboard_keyboard_action" },
            expected = "the real dashboard exposes six localized keyboard actions",
            repair = "Restore the six-action Snacks dashboard profile and live locale refresh.",
        },
        {
            id = "CLARITY_RUNTIME_HELP_CONTRACT",
            kind = "behavior_contract",
            owner = "config.health",
            scenarios = { "file_ui" },
            flags = {
                "health_readonly",
                "health_locale_roundtrip",
                "health_routes_complete",
                "health_keyboard_close",
                "log_health_route",
                "log_readonly",
                "log_equivalent_route",
                "log_cleanup",
            },
            expected = "Health and compatibility log views are read-only, keyboard accessible, and live-localized",
            repair = "Restore Health route rendering, transactional refresh, and compatibility routes.",
        },
        {
            id = "CLARITY_RUNTIME_TERMINAL_CONTRACT",
            kind = "behavior_contract",
            owner = "plugins.terminal",
            scenarios = { "file_ui" },
            flags = {
                "terminal_mapping",
                "terminal_opened",
                "terminal_float",
                "terminal_numbers_hidden",
                "terminal_keyboard_close",
            },
            expected = "real <leader>tf input opens and closes the floating terminal",
            repair = "Restore the single promoted Snacks terminal toggle and terminal-local window policy.",
        },
        {
            id = "CLARITY_RUNTIME_GIT_OBSERVATION_CONTRACT",
            kind = "behavior_contract",
            owner = "config.actions.git",
            scenarios = { "file_ui" },
            flags = {
                "git_observation_views",
                "git_observation_safe",
                "repository_immutable",
            },
            expected = "all five Git observation views and negative inputs leave repository identity and bytes unchanged",
            repair = "Use fixed read-only Git argv and scratch views without picker confirms or mutation mappings.",
        },
        {
            id = "CLARITY_RUNTIME_FORMATTING_CONTRACT",
            kind = "behavior_contract",
            owner = "conform.nvim + project configuration",
            scenarios = { "file_ui" },
            flags = {
                "formatter_present",
                "formatter_project_config",
                "formatter_no_style_args",
                "formatter_missing_detected",
                "formatter_missing_stable",
            },
            expected = "project configuration owns style; missing formatters are explicit and never trigger installation",
            repair = "Install the project formatter on PATH or use LSP fallback; do not add global style arguments.",
        },
        {
            id = "CLARITY_RUNTIME_DEPENDENCY_CONTRACT",
            kind = "behavior_contract",
            owner = "host toolchain + native Neovim",
            scenarios = { "file_ui" },
            flags = {
                "removed_dependencies_inactive",
                "no_mason_route",
                "blink_loaded",
                "native_snippet",
                "mini_pairs_input",
                "missing_lsp_no_install",
            },
            expected = "removed dependencies stay inactive while native snippets, completion, pairs, and no-install degradation work",
            repair = "Restore only the dependency whose isolated behavior gate fails; keep toolchain installation host-owned.",
        },
        {
            id = "CLARITY_RUNTIME_THEME_CONTRACT",
            kind = "behavior_contract",
            owner = "custom_colorblind_theme",
            scenarios = { "file_ui" },
            flags = { "static_theme_reload" },
            expected = "the static accessibility theme reloads without Lush and preserves resolved highlights",
            repair = "Restore the static colorscheme lifecycle and rerun resolved contrast tests.",
        },
        {
            id = "CLARITY_RUNTIME_EAGER_SERVICES",
            kind = "modules_loaded",
            owner = "config.lazy",
            modules = {
                "config.lazy",
                "config.capabilities",
                "config.i18n",
                "config.menu_i18n",
                "config.audit",
                "config.help",
                "config.health",
                "config.validation",
                "config.commands",
            },
            scenarios = { "empty_headless", "file_headless", "file_ui" },
            expected = "all eager Clarity services loaded",
            repair = "Restore the explicit eager service setup in config.lazy.",
        },
    },
}
