return {
    schema_version = 1,
    scenarios = {
        empty_headless = {
            kind = "headless",
            description = "Empty startup without an attached UI",
        },
        file_headless = {
            kind = "headless",
            description = "Tracked file startup without an attached UI",
        },
        file_ui = {
            kind = "attached_ui",
            description = "Tracked file startup with a real embedded UI",
        },
    },
    modules = {
        ["config.lazy"] = { class = "pre_plugin", owner = "bootstrap" },
        ["config.options"] = { class = "pre_plugin", owner = "LazyVimOptions" },
        ["config.autocmds"] = { class = "lifecycle", owner = "LazyVimAutocmds" },
        ["config.keymaps"] = { class = "lifecycle", owner = "LazyVimKeymaps" },
        ["config.capabilities"] = { class = "eager_service", owner = "config.audit" },
        ["config.i18n"] = { class = "eager_service", owner = "config.lazy" },
        ["config.menu_i18n"] = { class = "eager_service", owner = "config.lazy" },
        ["config.audit"] = { class = "eager_service", owner = "config.lazy" },
        ["config.help"] = { class = "eager_service", owner = "config.lazy" },
        ["config.health"] = { class = "eager_service", owner = "config.lazy" },
        ["config.validation"] = { class = "eager_service", owner = "config.lazy" },
        ["config.commands"] = { class = "eager_service", owner = "config.lazy" },
        ["config.diagnostics"] = { class = "on_demand", owner = "Clarity actions" },
        ["config.actions.fold"] = { class = "on_demand", owner = "config.keymaps" },
    },
    capabilities = {
        file_search = {
            surface = "<leader>ff",
            owner = "LazyVim picker",
            profile = "core",
            coverage = "planned",
            task = "RUNTIME-006",
        },
        text_search = {
            surface = "<leader>fw",
            owner = "config.keymaps",
            profile = "core",
            coverage = "planned",
            task = "RUNTIME-006",
        },
        explorer = {
            surface = "<leader>e",
            owner = "plugins.neo-tree",
            profile = "core",
            coverage = "planned",
            task = "NVIM-003",
        },
        code_fold = {
            surface = "<leader>cz",
            owner = "config.actions.fold",
            profile = "core",
            coverage = "covered",
        },
        line_wrap = {
            surface = "<leader>uw",
            owner = "config.keymaps",
            profile = "core",
            coverage = "covered",
        },
        terminal = {
            surface = "<leader>tf",
            owner = "plugins.terminal",
            profile = "core",
            coverage = "planned",
            task = "RUNTIME-006",
        },
        git_hunks = {
            surface = "<leader>ghs|ghr|ghp",
            owner = "plugins.git",
            profile = "development",
            coverage = "planned",
            task = "NVIM-006",
        },
        lsp_navigation = {
            surface = "gd|gr|gl",
            owner = "LazyVim LSP keymaps",
            profile = "development",
            coverage = "planned",
            task = "RUNTIME-006",
        },
        formatting = {
            surface = "LazyVim format",
            owner = "plugins.formatting",
            profile = "development",
            coverage = "planned",
            task = "NVIM-005",
        },
        parser = {
            surface = "Tree-sitter highlight/fold",
            owner = "plugins.treesitter",
            profile = "development",
            coverage = "planned",
            task = "NVIM-007",
        },
        recovery = {
            surface = ":ClarityStart|<leader>hh",
            owner = "config.help",
            profile = "core",
            coverage = "planned",
            task = "UX-002",
        },
        language = {
            surface = ":ClarityLanguage",
            owner = "config.i18n",
            profile = "core",
            coverage = "planned",
            task = "RUNTIME-006",
        },
        audit = {
            surface = ":ClarityAudit",
            owner = "config.audit",
            profile = "core",
            coverage = "planned",
            task = "VALIDATE-003",
        },
        validation = {
            surface = ":ClarityValidate",
            owner = "config.validation",
            profile = "core",
            coverage = "planned",
            task = "VALIDATE-003",
        },
    },
    checks = {
        {
            id = "CLARITY_RUNTIME_OPTIONS_CONTRACT",
            kind = "module_phase",
            module = "config.options",
            owner = "LazyVimOptions",
            scenarios = { "empty_headless", "file_headless", "file_ui" },
            expected = "User:LazyVimOptions",
            repair = "Keep the nested Clarity runtime visible while LazyVim loads options.",
        },
        {
            id = "CLARITY_RUNTIME_AUTOCMDS_CONTRACT",
            kind = "autocmds_contract",
            module = "config.autocmds",
            owner = "LazyVimAutocmds",
            scenarios = { "file_headless", "file_ui" },
            expected = "loaded at User:LazyVimAutocmds with owned line-number autocmds",
            repair = "Restore natural config.autocmds discovery before file startup completes.",
        },
        {
            id = "CLARITY_RUNTIME_EDITING_DEFAULTS",
            kind = "editing_defaults",
            owner = "config.options",
            scenarios = { "empty_headless", "file_headless", "file_ui" },
            expected = "number=true relativenumber=false wrap=true linebreak=true breakindent=true",
            repair = "Apply Clarity editing defaults after LazyVim defaults through config.options.",
        },
        {
            id = "CLARITY_RUNTIME_KEYMAP_CONTRACT",
            kind = "keymap_contract",
            module = "config.keymaps",
            owner = "LazyVimKeymaps",
            scenarios = { "file_ui" },
            expected = "loaded at User:LazyVimKeymaps; wrap owned by config.keymaps; fold owned by config.actions.fold; both executable",
            repair = "Keep the nested runtime visible through UIEnter/VeryLazy and restore Clarity keymaps.",
        },
        {
            id = "CLARITY_RUNTIME_EAGER_SERVICES",
            kind = "modules_loaded",
            owner = "config.lazy",
            modules = {
                "config.lazy",
                "config.capabilities",
                "config.i18n",
                "config.menu_i18n",
                "config.audit",
                "config.help",
                "config.health",
                "config.validation",
                "config.commands",
            },
            scenarios = { "empty_headless", "file_headless", "file_ui" },
            expected = "all eager Clarity services loaded",
            repair = "Restore the explicit eager service setup in config.lazy.",
        },
    },
}
